const clubsData = [
  {
    id: 'acfb',
    name: 'Associació Catalana de Futbol Botons',
    abbr: 'ACFB',
    logo: 'images/logos/logo-acfb.png',
    lat: 41.4078,
    lng: 2.1279,
    location: 'Barcelona (La Bonanova)',
    address: 'Casal Mossèn Lluís Vidal, C/ Bigai 12, 1r pis',
    phone: '650 124 486',
    hours: 'Dl–Dj 18–21 h · Dissabtes de torneig',
    website: 'https://www.futbolbotons.com',
    email: ''
  },
  {
    id: 'afbo',
    name: 'Associació de Futbol Botons d\'Osona',
    abbr: 'AFBO',
    logo: 'images/logos/logo-afbo.jpg',
    lat: 41.7926,
    lng: 2.2239,
    location: 'Centelles (Osona)',
    address: 'Ronda les Tàpies 48, Centelles',
    phone: '',
    hours: 'Dimecres ~20:15 h · Diumenge al migdia',
    website: 'http://futbolambbotons.blogspot.com',
    email: ''
  },
  {
    id: 'arfb',
    name: 'Associació Reusenca de Futbol Botons',
    abbr: 'ARFB',
    logo: 'images/logos/logo-arfb.jpg',
    lat: 41.1559,
    lng: 1.1065,
    location: 'Reus',
    address: 'C/ Robuster 36-1, 43204 Reus',
    phone: '',
    hours: '',
    website: '',
    email: 'caesargalio@hotmail.com'
  },
  {
    id: 'bap',
    name: 'Botonaires Associats Palautordera',
    abbr: 'BAP',
    logo: 'images/logos/logo-bap.png',
    lat: 41.6830,
    lng: 2.4580,
    location: 'Palautordera (Vallès Oriental)',
    address: '',
    phone: '',
    hours: '',
    website: 'https://bapfutbolbotons.blogspot.com',
    email: 'bapfutbolbotons@gmail.com'
  },
  {
    id: 'baixllobregat',
    name: 'Club Futbol Botons Baix Llobregat',
    abbr: 'CFBBL',
    logo: 'images/logos/logo-baixllobregat.png',
    lat: 41.3550,
    lng: 2.0700,
    location: 'Baix Llobregat',
    address: '',
    phone: '',
    hours: '',
    website: '',
    email: ''
  },
  {
    id: 'cfbb',
    name: 'Club Futbol Botons Barcelona',
    abbr: 'CFBB',
    logo: 'images/logos/logo-cfbb.png',
    lat: 41.37840228287077,
    lng: 2.1587632288565213,
    location: 'Barcelona (Eixample)',
    address: 'C/ Viladomat 75, 08015 Barcelona',
    phone: '',
    hours: '',
    website: 'http://cfbb.futbolbotons.cat/',
    email: 'contacte.cfbb@gmail.com'
  },
  {
    id: 'fomenthortenc',
    name: 'Foment Hortenc',
    abbr: 'FH',
    logo: 'images/logos/logo-fomenthortenc.png',
    lat: 41.4345,
    lng: 2.1502,
    location: 'Barcelona (Horta)',
    address: 'C/ Alt de Mariner 15, 08032 Barcelona',
    phone: '93 429 10 40',
    hours: '',
    website: 'https://www.fomenthortenc.cat/web2.0/futbol-botons/',
    email: 'futbolbotons@fomenthortenc.cat'
  }
];
