const clubsData = [
  {
    id: 'acfb',
    name: 'Associació Catalana de Futbol Botons',
    abbr: 'ACFB',
    logo: 'images/logos/logo-acfb.png',
    lat: 41.4078,
    lng: 2.1279,
    location: 'Barcelona (La Bonanova)',
    address: 'Casal Mossèn Lluís Vidal, C/ Bigai 12, 1r pis',
    phone: '650 124 486',
    hours: 'Dl–Dj 18–21 h · Dissabtes de torneig',
    website: 'https://www.futbolbotons.com',
    email: ''
  },
  {
    id: 'afbo',
    name: 'Associació de Futbol Botons d\'Osona',
    abbr: 'AFBO',
    logo: 'images/logos/logo-afbo.png',
    lat: 41.79544267938633,
    lng: 2.2197299537180997,
    location: 'Centelles (Osona)',
    address: 'Ronda les Tàpies 10, 08540 Centelles',
    phone: '722453910',
    hours: 'Dimecres ~20:15 h · Diumenge al migdia',
    website: 'http://futbolambbotons.blogspot.com',
    email: 'botons.osona@gmail.com',
    instagram: 'https://www.instagram.com/futbolbotons'
  },
  {
    id: 'arfb',
    name: 'Associació Reusenca de Futbol Botons',
    abbr: 'ARFB',
    logo: 'images/logos/logo-arfb.jpg',
    lat: 41.1559,
    lng: 1.1065,
    location: 'Reus',
    address: 'C/ Robuster 36-1, 43204 Reus',
    phone: '',
    hours: '',
    website: '',
    email: 'caesargalio@hotmail.com'
  },
  {
    id: 'bap',
    name: 'Club Futbol Botons Atlètic Palautordera',
    abbr: 'CFBAP',
    logo: 'images/logos/logo-bap.png',
    lat: 41.6830,
    lng: 2.4580,
    location: 'Santa Maria de Palautordera (Vallès Oriental)',
    address: '',
    phone: '',
    hours: '',
    website: 'https://bapfutbolbotons.blogspot.com',
    email: 'bapfutbolbotons@gmail.com'
  },
  {
    id: 'baixllobregat',
    name: 'Club Futbol Botons Baix Llobregat',
    abbr: 'CFBBL',
    logo: 'images/logos/logo-baixllobregat.png',
    lat: 41.380418932656646,
    lng: 2.086512267837823,
    location: 'Esplugues de Llobregat (Baix Llobregat)',
    address: 'Complex Esportiu Municipal Les Moreres, C/ de l\'Església 79, 08950 Esplugues de Llobregat',
    phone: '',
    hours: 'Divendres de 18:00 a 20:00',
    website: '',
    email: 'espluguesfba@gmail.com'
  },
  {
    id: 'cfbb',
    name: 'Club Futbol Botons Barcelona',
    abbr: 'CFBB',
    logo: 'images/logos/logo-cfbb.png',
    lat: 41.37840228287077,
    lng: 2.1587632288565213,
    location: 'Barcelona (Eixample)',
    address: 'C/ Viladomat 75, 08015 Barcelona',
    phone: '',
    hours: 'Dijous de 17:00 a 20:00',
    website: 'http://cfbb.futbolbotons.cat/',
    email: 'contacte.cfbb@gmail.com'
  },
  {
    id: 'fomenthortenc',
    name: 'Futbol Botons Foment Hortenc',
    abbr: 'FBFH',
    logo: 'images/logos/logo-fomenthortenc.png',
    lat: 41.4345,
    lng: 2.1502,
    location: 'Barcelona (Horta)',
    address: 'C/ Alt de Mariner 15, 08032 Barcelona',
    phone: '646 394 456',
    hours: 'Dimarts de 19:30 a 21:30 · Possibilitat de jugar a altres hores',
    website: 'https://www.fomenthortenc.cat/web2.0/futbol-botons/',
    email: 'futbolbotons@fomenthortenc.cat',
    instagram: 'https://www.instagram.com/futbolbotonsfomenthortenc'
  }
];
